version: '3'

services:
  web:
    build: ./web
    ports:
      - "3000:3000"
  db:
    build: ./db
    ports:
      - "27017:27017"
  seed:
    build: ./seed
    depends_on:
      - db
  server:
    build: ./server
    depends_on:
      - db
    ports:
      - "8080:8080"
